window.gameData = window.gameData || {};
window.gameData.countries = [
    // South America
    { name: "Argentina", code: "ar", continent: "South America" },
    { name: "Bolivia", code: "bo", continent: "South America" },
    { name: "Brazil", code: "br", continent: "South America" },
    { name: "Chile", code: "cl", continent: "South America" },
    { name: "Colombia", code: "co", continent: "South America" },
    { name: "Ecuador", code: "ec", continent: "South America" },
    { name: "Guyana", code: "gy", continent: "South America" },
    { name: "Paraguay", code: "py", continent: "South America" },
    { name: "Peru", code: "pe", continent: "South America" },
    { name: "Suriname", code: "sr", continent: "South America" },
    { name: "Uruguay", code: "uy", continent: "South America" },
    { name: "Venezuela", code: "ve", continent: "South America" },

    // North America (includes Central and Caribbean)
    { name: "United States", code: "us", continent: "North America" },
    { name: "Canada", code: "ca", continent: "North America" },
    { name: "Mexico", code: "mx", continent: "North America" },
    { name: "Bahamas", code: "bs", continent: "North America" },
    { name: "Belize", code: "bz", continent: "North America" },
    { name: "Costa Rica", code: "cr", continent: "North America" },
    { name: "Cuba", code: "cu", continent: "North America" },
    { name: "Dominican Republic", code: "do", continent: "North America" },
    { name: "El Salvador", code: "sv", continent: "North America" },
    { name: "Guatemala", code: "gt", continent: "North America" },
    { name: "Haiti", code: "ht", continent: "North America" },
    { name: "Honduras", code: "hn", continent: "North America" },
    { name: "Jamaica", code: "jm", continent: "North America" },
    { name: "Nicaragua", code: "ni", continent: "North America" },
    { name: "Panama", code: "pa", continent: "North America" },
    { name: "Trinidad and Tobago", code: "tt", continent: "North America" },

    // Europe
    { name: "Albania", code: "al", continent: "Europe" },
    { name: "Armenia", code: "am", continent: "Europe" },
    { name: "Austria", code: "at", continent: "Europe" },
    { name: "Belarus", code: "by", continent: "Europe" },
    { name: "Belgium", code: "be", continent: "Europe" },
    { name: "Bosnia and Herzegovina", code: "ba", continent: "Europe" },
    { name: "Bulgaria", code: "bg", continent: "Europe" },
    { name: "Croatia", code: "hr", continent: "Europe" },
    { name: "Cyprus", code: "cy", continent: "Europe" },
    { name: "Czech Republic", code: "cz", continent: "Europe" },
    { name: "Denmark", code: "dk", continent: "Europe" },
    { name: "Estonia", code: "ee", continent: "Europe" },
    { name: "Finland", code: "fi", continent: "Europe" },
    { name: "France", code: "fr", continent: "Europe" },
    { name: "Georgia", code: "ge", continent: "Europe" },
    { name: "Germany", code: "de", continent: "Europe" },
    { name: "Greece", code: "gr", continent: "Europe" },
    { name: "Hungary", code: "hu", continent: "Europe" },
    { name: "Iceland", code: "is", continent: "Europe" },
    { name: "Ireland", code: "ie", continent: "Europe" },
    { name: "Italy", code: "it", continent: "Europe" },
    { name: "Kosovo", code: "_1", continent: "Europe" },
    { name: "Latvia", code: "lv", continent: "Europe" },
    { name: "Lithuania", code: "lt", continent: "Europe" },
    { name: "Luxembourg", code: "lu", continent: "Europe" },
    { name: "Moldova", code: "md", continent: "Europe" },
    { name: "Montenegro", code: "me", continent: "Europe" },
    { name: "Netherlands", code: "nl", continent: "Europe" },
    { name: "North Macedonia", code: "mk", continent: "Europe" },
    { name: "Norway", code: "no", continent: "Europe" },
    { name: "Poland", code: "pl", continent: "Europe" },
    { name: "Portugal", code: "pt", continent: "Europe" },
    { name: "Romania", code: "ro", continent: "Europe" },
    { name: "Russia", code: "ru", continent: "Europe" },
    { name: "Serbia", code: "rs", continent: "Europe" },
    { name: "Slovakia", code: "sk", continent: "Europe" },
    { name: "Slovenia", code: "si", continent: "Europe" },
    { name: "Spain", code: "es", continent: "Europe" },
    { name: "Sweden", code: "se", continent: "Europe" },
    { name: "Switzerland", code: "ch", continent: "Europe" },
    { name: "Ukraine", code: "ua", continent: "Europe" },
    { name: "United Kingdom", code: "gb", continent: "Europe" },

    // Asia
    { name: "Afghanistan", code: "af", continent: "Asia" },
    { name: "Azerbaijan", code: "az", continent: "Asia" },
    { name: "Bangladesh", code: "bd", continent: "Asia" },
    { name: "Bhutan", code: "bt", continent: "Asia" },
    { name: "Brunei", code: "bn", continent: "Asia" },
    { name: "Cambodia", code: "kh", continent: "Asia" },
    { name: "China", code: "cn", continent: "Asia" },
    { name: "East Timor", code: "tl", continent: "Asia" },
    { name: "India", code: "in", continent: "Asia" },
    { name: "Indonesia", code: "id", continent: "Asia" },
    { name: "Iran", code: "ir", continent: "Asia" },
    { name: "Iraq", code: "iq", continent: "Asia" },
    { name: "Israel", code: "il", continent: "Asia" },
    { name: "Japan", code: "jp", continent: "Asia" },
    { name: "Jordan", code: "jo", continent: "Asia" },
    { name: "Kazakhstan", code: "kz", continent: "Asia" },
    { name: "Kuwait", code: "kw", continent: "Asia" },
    { name: "Kyrgyzstan", code: "kg", continent: "Asia" },
    { name: "Laos", code: "la", continent: "Asia" },
    { name: "Lebanon", code: "lb", continent: "Asia" },
    { name: "Malaysia", code: "my", continent: "Asia" },
    { name: "Mongolia", code: "mn", continent: "Asia" },
    { name: "Myanmar", code: "mm", continent: "Asia" },
    { name: "Nepal", code: "np", continent: "Asia" },
    { name: "North Korea", code: "kp", continent: "Asia" },
    { name: "Oman", code: "om", continent: "Asia" },
    { name: "Pakistan", code: "pk", continent: "Asia" },
    { name: "Palestine", code: "ps", continent: "Asia" },
    { name: "Philippines", code: "ph", continent: "Asia" },
    { name: "Qatar", code: "qa", continent: "Asia" },
    { name: "Saudi Arabia", code: "sa", continent: "Asia" },
    { name: "South Korea", code: "kr", continent: "Asia" },
    { name: "Sri Lanka", code: "lk", continent: "Asia" },
    { name: "Syria", code: "sy", continent: "Asia" },
    { name: "Taiwan", code: "tw", continent: "Asia" },
    { name: "Tajikistan", code: "tj", continent: "Asia" },
    { name: "Thailand", code: "th", continent: "Asia" },
    { name: "Turkey", code: "tr", continent: "Asia" },
    { name: "Turkmenistan", code: "tm", continent: "Asia" },
    { name: "United Arab Emirates", code: "ae", continent: "Asia" },
    { name: "Uzbekistan", code: "uz", continent: "Asia" },
    { name: "Vietnam", code: "vn", continent: "Asia" },
    { name: "Yemen", code: "ye", continent: "Asia" },

    // Africa
    { name: "Algeria", code: "dz", continent: "Africa" },
    { name: "Angola", code: "ao", continent: "Africa" },
    { name: "Benin", code: "bj", continent: "Africa" },
    { name: "Botswana", code: "bw", continent: "Africa" },
    { name: "Burkina Faso", code: "bf", continent: "Africa" },
    { name: "Burundi", code: "bi", continent: "Africa" },
    { name: "Cameroon", code: "cm", continent: "Africa" },
    { name: "Central African Republic", code: "cf", continent: "Africa" },
    { name: "Chad", code: "td", continent: "Africa" },
    { name: "DR Congo", code: "cd", continent: "Africa" },
    { name: "Republic of the Congo", code: "cg", continent: "Africa" },
    { name: "Djibouti", code: "dj", continent: "Africa" },
    { name: "Egypt", code: "eg", continent: "Africa" },
    { name: "Equatorial Guinea", code: "gq", continent: "Africa" },
    { name: "Eritrea", code: "er", continent: "Africa" },
    { name: "Eswatini", code: "sz", continent: "Africa" },
    { name: "Ethiopia", code: "et", continent: "Africa" },
    { name: "Gabon", code: "ga", continent: "Africa" },
    { name: "Gambia", code: "gm", continent: "Africa" },
    { name: "Ghana", code: "gh", continent: "Africa" },
    { name: "Guinea", code: "gn", continent: "Africa" },
    { name: "Guinea-Bissau", code: "gw", continent: "Africa" },
    { name: "Ivory Coast", code: "ci", continent: "Africa" },
    { name: "Kenya", code: "ke", continent: "Africa" },
    { name: "Lesotho", code: "ls", continent: "Africa" },
    { name: "Liberia", code: "lr", continent: "Africa" },
    { name: "Libya", code: "ly", continent: "Africa" },
    { name: "Madagascar", code: "mg", continent: "Africa" },
    { name: "Malawi", code: "mw", continent: "Africa" },
    { name: "Mali", code: "ml", continent: "Africa" },
    { name: "Mauritania", code: "mr", continent: "Africa" },
    { name: "Morocco", code: "ma", continent: "Africa" },
    { name: "Mozambique", code: "mz", continent: "Africa" },
    { name: "Namibia", code: "na", continent: "Africa" },
    { name: "Niger", code: "ne", continent: "Africa" },
    { name: "Nigeria", code: "ng", continent: "Africa" },
    { name: "Rwanda", code: "rw", continent: "Africa" },
    { name: "Senegal", code: "sn", continent: "Africa" },
    { name: "Sierra Leone", code: "sl", continent: "Africa" },
    { name: "Somalia", code: "so", continent: "Africa" },
    { name: "South Africa", code: "za", continent: "Africa" },
    { name: "South Sudan", code: "ss", continent: "Africa" },
    { name: "Sudan", code: "sd", continent: "Africa" },
    { name: "Tanzania", code: "tz", continent: "Africa" },
    { name: "Togo", code: "tg", continent: "Africa" },
    { name: "Tunisia", code: "tn", continent: "Africa" },
    { name: "Uganda", code: "ug", continent: "Africa" },
    { name: "Zambia", code: "zm", continent: "Africa" },
    { name: "Zimbabwe", code: "zw", continent: "Africa" },

    // Oceania
    { name: "Australia", code: "au", continent: "Oceania" },
    { name: "Fiji", code: "fj", continent: "Oceania" },
    { name: "New Zealand", code: "nz", continent: "Oceania" },
    { name: "Papua New Guinea", code: "pg", continent: "Oceania" },
    { name: "Solomon Islands", code: "sb", continent: "Oceania" },
    { name: "Vanuatu", code: "vu", continent: "Oceania" }
];

